
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: chatr
type: Opaque
stringData:
  JWT_SECRET: k+lr9wyW7pn7gIIiQYGcKy37HAJnGs+T4EFyFqxJljs=
  MONGO_DB_URI: mongodb://chatr_admin:HoneyBump6969@mongodb:27017/chatapp?authSource=admin
