apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: chatr
data:
  MONGO_DB_URI: mongodb://mongodb:27017/chatapp
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  ALLOWED_ORIGINS: http://localhost
