
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  labels:
    {{- include "chatr.componentLabels" (dict "component" "backend" "context" .) | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}

  MONGO_USERNAME: {{ .Values.secrets.mongo.username | quote }}
  MONGO_PASSWORD: {{ .Values.secrets.mongo.password | quote }}
